# Jekyll Configuration File
# WARNING: This file is NOT reloaded automatically when using 'bundle exec jekyll serve'.
# After changes, restart the server process.

# Theme Configuration
minimal_mistakes_skin: sunrise
remote_theme: mmistakes/minimal-mistakes@4.24.0

# Core Site Settings
locale: "en_US"
title: &site_title "Barrosa Stay"
title_separator: "-"
subtitle: "Stay at Barrosa, Your Perfect Staycation"
name: &author_name "Marco Grimaldi"
email: &author_email "staybarrosa@gmail.com"
github_username: staybarrosa
description: &site_description >- # Multiline description
  Barrosa Stay is an vacation apartment located next to the beautiful Sancti Petri and Barrosa beach in
  Chiclana de la Frontera, Cadiz, Spain. Enjoy a perfect staycation with stunning sea views,
  modern amenities, and easy access to local attractions. Book your stay today for an unforgettable
  experience at Barrosa Stay!
url: &site_url "https://staybarrosa.com"  # Changed to CNAME URL
baseurl: ""  # the subpath of your site, e.g. "/blog"
repository: "staybarrosa/staybarrosa.github.io"
logo: &site_logo "/assets/images/sancti-petri-gh.jpg"
search: true
search_full_content: true
search_provider: lunr

# SEO Settings
seo:
  title: *site_title
  name: *author_name
  email: *author_email
  description: *site_description
  url: *site_url
  logo: *site_logo
  title_separator: "-"
  author: *author_name
  # SEO Keywords
  keywords: >-
    Barrosa Stay, Vacation Rentals, Holiday Homes,
    Beachfront Properties, Family Getaways, Romantic Escapes,
    Budget-Friendly Stays, Travel Destinations,
    Local Attractions, Vacation Planning, Travel Tips, Guest Reviews,
    Seasonal Offers, Last-Minute Deals, Extended Stays

  # Webmaster Verification
  verify:
    google: "" # Replace with your actual verification code
    bing: ""  # Add Bing verification later if needed
    
  # Social Media
  social:
    github: "staybarrosa"
  
  # Open Graph
  og:
    type: "website"
    image: *site_logo
    image_alt: "Barrosa Stay Website Logo"

# Build settings
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Outputting
permalink: /:categories/:title/
paginate: 5
paginate_path: /page:num/
timezone: Europe/Rome

# Files
include:
  - _pages
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache
  - jemoji
  - jekyll-seo-tag
  - jekyll-redirect-from

# mimic GitHub Pages with --safe
whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache
  - jemoji

# Author Information
author:
  name: *author_name
  # avatar: "/assets/images/xxx.jpg"
  bio: "Staying at Barrosa, Your Perfect Staycation"
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/staybarrosa"
    - label: "Website"
      icon: "fas fa-link"
      url: *site_url

# Footer Configuration
footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/staybarrosa"
    - label: "Website"
      icon: "fas fa-link"
      url: *site_url

# Content Defaults
defaults:
  # Post Defaults
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
      toc: true
      toc_sticky: true
  
  # Page Defaults
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true
      toc: true
      toc_sticky: true

# Archives
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
year_archive:
  type: liquid
  path: /posts/